web/controllers/account.py
# -*- coding: UTF-8 -*-
from flask import Blueprint, render_template, request, jsonify, flash, g, abort, redirect, url_for
from ..forms import DepartmentForm, UserForm, ModifyUserForm
from ..models import db, Department, User, UserInfo
from ..utils.permissions import require_admin, require_user
from ..utils import get_server_info
from datetime import datetime

bp = Blueprint('account', __name__)


@bp.route('/accounts')
def accounts():
    pass

@bp.route('/change_psw')
def change_psw():
    pass


@bp.route('/manage', methods=['GET', 'POST'])
@require_admin
def manage():
    department_form = DepartmentForm()
    if department_form.validate_on_submit():
        name = department_form.name.data
        dp = Department(name=name)
        db.session.add(dp)
        db.session.commit()
    departments = Department.query
    return render_template('admin/manage.html', page_name='manage_dp', department_form=department_form,
                           departments=departments)


@bp.route('/del_department', methods=['POST'])
@require_admin
def del_department():
    did = request.form.get('did', None, int)
    dp = Department.query.filter_by(id=did).first()
    if not dp:
        return jsonify({'status': 'error', 'message': '删除失败'})
    db.session.delete(dp)
    db.session.commit()
    return jsonify({'status': 'ok', 'did': did})


@bp.route('/user_manage', defaults={'page': 1})
@bp.route('/user_manage/<int:page>')
@require_admin
def user_manage(page):
    per = 10
    users = User.query
    for u in users:
        get_server_info.set_user_repo_and_ip(u.email)
    pages = User.query.paginate(page, per, False)
    # print pages
    return render_template('admin/user_manage.html', pages=pages, page_name='manage_user')

@bp.route('/add_user', methods=['GET', 'POST'])
@require_admin
def add_user():
    title = '添加用户'
    form = UserForm()
    form.depart_id.choices = [(0, '请选择')]
    form.depart_id.choices.extend([(d.id, d.name) for d in Department.query])
    if form.validate_on_submit():
        user = User()
        user.name = form.name.data
        user.password = form.password.data
        user.hash_psw()
        user.email = form.email.data
        user.contact = form.contact.data
        user.role = form.role.data
        user.ip = form.ip.data
        user.department_id = form.depart_id.data
        info = UserInfo(user=user)
        db.session.add(user)
        db.session.add(info)
        # print user.role
        db.session.commit()
        flash('添加成功')
        form.data.clear()
    return render_template('admin/add_user.html', form=form, title=title)


@bp.route('/modify_psw')
@require_user
def modify_psw():
    new_pwd = ''
    return render_template('admin/modify_psw.html')


@bp.route('/modify_user_info/<int:uid>', methods=['GET', 'POST'])
@require_user
def modify_user_info(uid):
    title = '修改信息'
    user = User.query.get_or_404(uid)
    if g.user.role != 'admin' and g.user.id != uid:
        abort(404)
    form = ModifyUserForm()
    form.depart_id.choices = [(0, '请选择')]
    form.depart_id.choices.extend([(d.id, d.name) for d in Department.query])
    if request.method == 'GET':
        form.name.data = user.name
        form.email.data = user.email
        form.ip.data = user.ip
        form.role.data = user.role
        form.contact.data = user.contact
        form.depart_id.data = user.department_id
    if form.validate_on_submit(): #POST
        user.name = form.name.data
        if form.password.data:
            user.password = form.password.data
            user.hash_psw()
            user.renew_at = datetime.now()
        user.role = form.role.data
        user.contact = form.contact.data
        user.email = form.email.data
        user.department_id = form.depart_id.data
        user.ip = form.ip.data
        db.session.commit()
        flash("修改成功!")
        if g.user.role == 'admin':
            return redirect(url_for('account.user_manage'))
        return redirect(url_for('site.index'))
    return render_template('admin/add_user.html', form=form, title=title)

@bp.route('/delete_user', methods=['POST'])
@require_admin
def delete_user():
    uid = request.form.get('uid', None, int)
    user = User.query.filter_by(id=uid).first()
    map(db.session.delete, user.userInfo)
    if not user:
        return jsonify({'status': 'error', 'message': '删除失败'})
    if user.id == g.user.id:
        return jsonify({'status': 'error', 'message': '不能删除自己的管理员账号'})
    db.session.delete(user)
    db.session.commit()
    return jsonify({'status': 'ok', 'uid': uid})

web/controllers/site.py
# -*- coding: UTF-8 -*-

from flask import Blueprint, current_app, render_template, redirect, url_for, g, flash, \
    request, make_response, Response
from ..models import db, User, Department
from ..forms.account import LoginForm, ModifyPsw
from ..utils.account import signin_user, signout_user
from ..utils.permissions import require_user
from ..utils.get_server_info import set_user_repo_and_ip
from werkzeug import security
from datetime import datetime
import os

bp = Blueprint('site', __name__)

@bp.route('/', methods=['GET'],  defaults={'page': 1})
@bp.route('/<int:page>')
@require_user
def index(page):
    uid = request.args.get('uid')
    if not uid or g.user.role != 'admin': # 非管理员用户只能看到自己的
        uid = g.user.id
    departs = Department.query
    per = 10
    pages = User.query.filter(User.role == 'client').paginate(page, per, False)
    return render_template('site/index.html', departs=departs, pages=pages, cur=uid), 200

@bp.route('/tt')
def tt():
    c = request.cookies.get('tt')
    print c
    r = Response()
    r.set_cookie('tt', '123')
    return r

@bp.route('/view_log')
def view_log():
    uid = request.args.get('uid')
    if not uid or g.user.role != 'admin': # 非管理员用户只能看到自己的
        uid = g.user.id
    file_name = request.args.get('file_name')
    config = current_app.config
    root = config.get('UPLOADS_DEST') + str(uid) + '/'
    pt = root + file_name
    if not os.path.exists(pt):
        return "文件不存在"
    with open(pt, 'r') as f:
        content = f.read()
    response = make_response(content)
    response.headers['Content-Type'] = 'text/plain; charset=utf-8'
    return response

@bp.route('/download_log')
def download_log():
    uid = request.args.get('uid')
    if not uid or g.user.role != 'admin': # 非管理员用户只能看到自己的
        uid = g.user.id
    file_name = request.args.get('file_name')
    config = current_app.config
    root = config.get('UPLOADS_DEST') + str(uid) + '/'
    pt = root + file_name
    if not os.path.exists(pt):
        return "文件不存在"
    with open(pt, 'r') as f:
        content = f.read()
    response = make_response(content)
    response.headers['Content-Type'] = 'application/octet-stream'
    response.headers['Content-Disposition'] = 'attachment; filename=' + file_name
    return response

@bp.route('/db')
def db_test():
    user = User(name=u'管理员', email='admin@qq.com', password='123456', role='admin')
    user.hash_psw()
    db.session.add(user)
    db.session.commit()
    return '用户人数:%d' % User.query.count()

@bp.route('/test')
def test():
    hsh = security.generate_password_hash('hash1')
    print str(security.check_password_hash(hsh, 'hash1'))
    return render_template('css_test.html')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        signin_user(form.user, form.permanent.data)
        days = form.user.get_expire_day()
        set_user_repo_and_ip(form.email.data)
        # print days
        if 0 < days < 10:
            flash('你的账号还有%d天就过期，请尽快修改密码' % days)
        else:
            flash('登陆成功')
        return redirect(url_for('site.index'))
    return render_template('site/login.html', form=form, hide_nav=True)

@bp.route('/logout')
def logout():
    if g.user:
        flash('退出')
        signout_user()
    return redirect(url_for('site.index'))

@bp.route('/modify_psw', methods=['GET', 'POST'])
@require_user
def modify_psw():
    uid = request.args.get('uid')
    modify_form = ModifyPsw()
    if modify_form.validate_on_submit():
        user = User.query.get_or_404(uid)
        user.password = modify_form.password.data
        user.hash_psw()
        user.renew_at = datetime.now()
        db.session.commit()
        flash('修改成功，新密码有效期是30天！')
        return redirect(url_for('site.index'))
    return render_template('site/modify_psw.html', modify_form=modify_form, cur=uid)

web/controllers/status.py
# -*- coding: UTF-8 -*-
from flask import Blueprint, render_template, jsonify, g, request, current_app
from ..models import Department, User, DiskStatus, db, UploadStatus, UploadSpeed, UserInfo
from ..utils.permissions import require_user
from ..utils import get_server_info
from datetime import datetime, timedelta
import json
import time

bp = Blueprint('status', __name__)


@bp.route('/test')
def test():
    ip = request.remote_addr
    return ip

@bp.route('/uploads', defaults={'page': 1})
@bp.route('/uploads/<int:page>')
@require_user
def uploads(page):
    uid = request.args.get('uid', None, int)
    if not uid:
        uid = g.user.id
    uploads = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == False).\
        group_by(UploadStatus.file_id)
    per = 10
    finishFiles = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == True)\
        .group_by(UploadStatus.file_id).order_by(UploadStatus.current.desc()).paginate(page, per, False)
    uploadStatus = []
    # print len(uploads.all())
    for u in uploads:
        up = {
            'tid': u.id,
            'file_id': u.file_id,
            'file_name': u.file_name,
            'total': u.total,
            'speed': u.speed,
            'cur': u.current,
            'update_time': u.update_time.strftime("%Y-%m-%d %H:%I:%S")
        }
        uploadStatus.append(up)
    departs = Department.query
    return render_template('status/uploads.html', departs=departs, finishFiles=finishFiles,
                           uploadStatus=json.dumps(uploadStatus))

@bp.route('/repo', defaults={'page': 1})
@bp.route('/repo/<int:page>')
@require_user
def repo(page):
    uid = request.args.get('uid', None, int)
    if not uid or g.user.role != 'admin': # 非管理员用户只能看到自己的
        uid = g.user.id
    suc = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == True, UploadStatus.status == True).\
        order_by(UploadStatus.update_time.desc())
    now = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == False, UploadStatus.status == True).\
        order_by(UploadStatus.update_time.desc()).first()
    userInfo = UserInfo.query.filter(UserInfo.uid == uid).first()
    repo_url = None
    if userInfo and userInfo.repo_id:
        repo_url = current_app.config.get('SEAFILE_API_URL')
        repo_url += userInfo.repo_id
    departs = Department.query
    count = 0
    if suc:
        count += suc.count()
    failed = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == True, UploadStatus.status == False).\
        order_by(UploadStatus.update_time.desc())
    if failed:
        count += failed.count()
    suc = suc.paginate(page, 15, False)
    failed = failed.paginate(page, 15, False)
    cur = uid
    return render_template('status/repo_status.html', cur=cur, repo_url=repo_url, departs=departs, count=count, failed=failed, suc=suc, now=now)


@bp.route('/upload_speed')
@require_user
def upload_speed():
    uid = request.args.get('uid', None, int)
    if not uid or g.user.role != 'admin': # 非管理员用户只能看到自己的
        uid = g.user.id
    early = UploadSpeed.query.filter(UploadSpeed.uid == uid).order_by(UploadSpeed.time_stamp.asc()).first()
    latest = UploadSpeed.query.filter(UploadSpeed.uid == uid).order_by(UploadSpeed.time_stamp.desc()).first()
    start = request.args.get('start', "")
    end = request.args.get('end', "")
    if not end:
        end_date = time.mktime(datetime.now().timetuple())
    else:
        end_date = datetime.strptime(end, "%Y-%m-%d %H:%M")
        end_date = time.mktime(end_date.timetuple())
        if latest and end_date < latest.time_stamp:
            end_date = latest.time_stamp
    if not start:
        start_date = end_date - 5 * 24 * 3600
    else:
        start_date = datetime.strptime(start, "%Y-%m-%d %H:%M")
        start_date = time.mktime(start_date.timetuple())
        if early and start_date < early.time_stamp:
            start_date = early.time_stamp
    # print uid, start,start_date, end, end_date
    status = UploadSpeed.query.filter(UploadSpeed.time_stamp < int(end_date), UploadSpeed.uid == uid,
                                       UploadSpeed.time_stamp > int(start_date)).group_by(UploadSpeed.time_stamp).order_by(UploadSpeed.time_stamp.asc())
    data = []
    for s in status:
        t = s.time_stamp
        data.append([t * 1000, s.speed])
    departs = Department.query
    return render_template('status/upload_speed.html', data=json.dumps(data), departs=departs, uid=uid,
                           start=start, end=end)


@bp.route('/current_speed', methods=['POST'])
def current_speed():
    uid = request.form.get('uid')
    speed = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish==False, UploadStatus.status == True).\
        order_by(UploadStatus.update_time.desc()).first()
    if not speed:
        return jsonify({'status': 'finish', 'message': '传输完成'})
    return jsonify({'status': 'ok', 'rate': speed.rate, 'percent': speed.percent, 'desc': speed.desc})

@bp.route('/file', methods=['POST'])
@require_user
def file():
    fid = request.form.get('tid', -1, int)
    u = UploadStatus.query.get_or_404(fid)
    data = {
        'tid': u.id,
        'cur': u.current,
        'speed': u.speed,
        'file_name': u.file_name,
        'total': u.total
    }
    return json.dumps(data)


@bp.route('/disk')
@require_user
def disk():
    uid = request.args.get('uid', None, int)
    if not uid or g.user.role != 'admin': # 非管理员用户只能看到自己的
        uid = g.user.id
    user = User.query.get_or_404(uid)
    su, st = get_server_info.get_server_disk(user.email)
    departs = Department.query
    # status = DiskStatus.query
    # client_info = status.order_by(DiskStatus.update_time.desc()).first()
    # su = client_info.used * 1000000
    # st = client_info.total * 100
    # print su, st
    current_app.logger.info("su:" + str(su) + " st:" + str(st))
    client_cur = []
    server_cur = []
    ct = None
    cu = None
    # if client_info:
    #     ct = client_info.total
    #     cu = client_info.used
    #     client_cur = [
    #         ['剩余空间', round((client_info.total - client_info.used) / (1 << 30), 2)],
    #         ['已使用的空间', round(client_info.used / (1 << 30), 2)]]
    if st:
        server_cur = [
            ['剩余空间', round((st - su) / (1 << 30), 2)],
            ['已使用的空间', round(su / (1 << 30), 2)]]
    return render_template('/status/disk.html', departs=departs, uid=uid, client_cur=json.dumps(client_cur),
                           client_total=ct, client_used =cu, server_cur=json.dumps(server_cur), server_total=st, server_used=su)

web/templates/css_test.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    {{ link('bower_components/bootstrap/dist/css/bootstrap.min.css') }}
    <style type="text/css">
        body {
            background: #f2dede;
        }

        .center {
            width: 900px;
            min-height: 200px;
            margin: 20px auto;
            display: block;
        }

        .show-grid [class ^="col-"] {
            padding-top: 10px;
            padding-bottom: 10px;
            background-color: #eee;
            background-color: rgba(86, 61, 124, .15);
            border: 1px solid rgba(86, 61, 124, .2);
        }

        .upload-wap {
            min-height: 200px;
        }

        .upload-wap .col-xs-7 {
            width: 90%;
        }

        .upload-wap .upload-item {
            background: #ffffff;
            height: 90px;
        }

        .upload-wap .upload-item .status {
            float: left;
            background: green;
            width: 90px;
            margin: 0px 10px;
            height: 90px;
            line-height: 90px;
            text-align: center;
            font-size: 19px;
            color: #ffffff;
        }

    </style>
</head>
<body>
<div class="row">
    浮块：
    <span class="caret"></span>
</div>
<span class="glyphicon glyphicon-search"></span>
<section class="center show-grid">
    <h2>栅格布局系统</h2>

    <div class="row">
        <div class="col-md-2 col-md-offset-3">2</div>
    </div>
    <div class="row">
        <div class="col-md-4">.col-md-4</div>
        <div class="col-xs-6 col-sm-3 col-xs-offset-5">.col-xs-6 .col-sm-4</div>
        <div class="col-md-4 col-md-offset-4">.col-md-4 .col-md-offset-4</div>
    </div>
</section>
<div class="show-grid">
    <div class="row">
        <div class="col-md-2">.col-md-4</div>
        <div class="col-xs-6 col-sm-4">.col-xs-6 .col-sm-4</div>
        <div class="col-md-4 col-md-offset-4">.col-md-4 .col-md-offset-4</div>
    </div>
</div>
<div class="center">
    <div class="upload-wap">
        <div class="col-xs-9">
            <div class="upload-item">
                <div class="status">
                    上传完成
                </div>
                <div class="col-xs-7 status-item">
                    <span>文件名：22 &nbsp;&nbsp;</span>
                    <span>上传时间:2014-10-9&nbsp;&nbsp;</span>
                    <span>文件大小: 80.9M&nbsp;&nbsp;</span>
                    <span>速度：70k/s&nbsp;&nbsp;</span>

                    <div class="progress">
                        <div class="progress-bar progress-bar-success progress-bar-striped active"
                             role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: 70%">70%
                        </div>
                    </div>
                </div>

                <div class="detail">
                    <table>
                        <tbody>
                        <tr>
                            <td class="key">文件名：</td>
                            <td>hao123.txt</td>
                        </tr>
                        <tr>
                            <td class="key">上传日期：</td>
                            <td>2014-12-11</td>
                        </tr>
                        <tr>
                            <td class="key">平均速度：</td>
                            <td>70k/s</td>
                        </tr>
                        <tr>
                            <td class="key">用时：</td>
                            <td>49s</td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

web/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block page_title %}{% endblock %}</title>
    {{ link('bower_components/bootstrap/dist/css/bootstrap.min.css') }}
    {{ link('css/layout.css') }}
    {% block page_css %}{% endblock %}
    {{ script('bower_components/jquery/dist/jquery.js') }}
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta charset="UTF-8">
</head>
<body>
{% with message = get_flashed_messages()[0] %}
    {% if message %}
        <div class="alert alert-error flash-message">
            <button data-dismiss="alert" class="close" type="button">×</button>
            {{ message }}
        </div>
    {% endif %}
{% endwith %}
{% if not hide_nav %}
    <div class="navbar-wrapper">
        <div class="container">

            <div class="navbar-inverse navbar-default navbar-fixed-top" style="background-color: rgb(195, 37, 36)">
                <div class="container" style="color: white">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" style="color: white" href="{{ url_for('site.index') }}#">容灾中心</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li><a href="{{ url_for('status.repo') }}">查看资料库同步状态</a></li>
                            <li><a href="{{ url_for('status.upload_speed') }}">查看网络传输速度</a></li>
                            <li><a href="{{ url_for('status.disk') }}">查看空间使用情况</a></li>
                            {% if g.user %}
                                {% if g.user.role == 'admin' %}
                                    <li><a href="{{ url_for('account.user_manage') }}">管理用户</a></li>
                                {% else %}
                                    <li><a href="{{ url_for('account.modify_user_info', uid=g.user.id) }}">修改密码</a></li>
                                {% endif %}
                            </ul><ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="{{ url_for('account.modify_user_info', uid=g.user.id) }}">你好!&nbsp;{{ g.user.name }}</a>
                                </li>
                                <li><a href="{{ url_for('site.logout') }}">退出</a></li>
                            {% else %}
                                </ul><ul class="nav navbar-nav navbar-right">
                                <li><a href="{{ url_for('site.login') }}">登陆</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endif %}


<div id="main-wap" class="container">
    {% block content %}{% endblock %}
</div>
<script type="text/javascript">
    var gLocals = {
        'csrf': "{{ csrf_token() }}",
        'site_domain': "{{ g_site_domain }}"
    };
</script>
{{ script('js/layout.js') }}
</body>
</html>