web/controllers/status.py
# -*- coding: UTF-8 -*-
from flask import Blueprint, render_template, jsonify, g, request, current_app
from ..models import Department, User, DiskStatus, db, UploadStatus, UploadSpeed, UserInfo
from ..utils.permissions import require_user
from ..utils import get_server_info
from datetime import datetime, timedelta
import json
import time

bp = Blueprint('status', __name__)


@bp.route('/test')
def test():
    ip = request.remote_addr
    return ip

@bp.route('/uploads', defaults={'page': 1})
@bp.route('/uploads/<int:page>')
@require_user
def uploads(page):
    uid = request.args.get('uid', None, int)
    if not uid:
        uid = g.user.id
    uploads = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == False).\
        group_by(UploadStatus.file_id)
    per = 10
    finishFiles = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == True)\
        .group_by(UploadStatus.file_id).order_by(UploadStatus.current.desc()).paginate(page, per, False)
    uploadStatus = []
    # print len(uploads.all())
    for u in uploads:
        up = {
            'tid': u.id,
            'file_id': u.file_id,
            'file_name': u.file_name,
            'total': u.total,
            'speed': u.speed,
            'cur': u.current,
            'update_time': u.update_time.strftime("%Y-%m-%d %H:%I:%S")
        }
        uploadStatus.append(up)
    departs = Department.query
    return render_template('status/uploads.html', departs=departs, finishFiles=finishFiles,
                           uploadStatus=json.dumps(uploadStatus))

@bp.route('/repo', defaults={'page': 1})
@bp.route('/repo/<int:page>')
@require_user
def repo(page):
    uid = request.args.get('uid', None, int)
    if not uid or g.user.role != 'admin': # 非管理员用户只能看到自己的
        uid = g.user.id
    suc = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == True, UploadStatus.status == True).\
        order_by(UploadStatus.update_time.desc())
    now = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == False, UploadStatus.status == True).\
        order_by(UploadStatus.update_time.desc()).first()
    userInfo = UserInfo.query.filter(UserInfo.uid == uid).first()
    repo_url = None
    if userInfo and userInfo.repo_id:
        repo_url = current_app.config.get('SEAFILE_API_URL')
        repo_url += userInfo.repo_id
    departs = Department.query
    count = 0
    if suc:
        count += suc.count()
    failed = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish == True, UploadStatus.status == False).\
        order_by(UploadStatus.update_time.desc())
    if failed:
        count += failed.count()
    suc = suc.paginate(page, 15, False)
    failed = failed.paginate(page, 15, False)
    cur = uid
    return render_template('status/repo_status.html', cur=cur, repo_url=repo_url, departs=departs, count=count, failed=failed, suc=suc, now=now)


@bp.route('/upload_speed')
@require_user
def upload_speed():
    uid = request.args.get('uid', None, int)
    if not uid or g.user.role != 'admin': # 非管理员用户只能看到自己的
        uid = g.user.id
    early = UploadSpeed.query.filter(UploadSpeed.uid == uid).order_by(UploadSpeed.time_stamp.asc()).first()
    latest = UploadSpeed.query.filter(UploadSpeed.uid == uid).order_by(UploadSpeed.time_stamp.desc()).first()
    start = request.args.get('start', "")
    end = request.args.get('end', "")
    if not end:
        end_date = time.mktime(datetime.now().timetuple())
    else:
        end_date = datetime.strptime(end, "%Y-%m-%d %H:%M")
        end_date = time.mktime(end_date.timetuple())
        if latest and end_date < latest.time_stamp:
            end_date = latest.time_stamp
    if not start:
        start_date = end_date - 5 * 24 * 3600
    else:
        start_date = datetime.strptime(start, "%Y-%m-%d %H:%M")
        start_date = time.mktime(start_date.timetuple())
        if early and start_date < early.time_stamp:
            start_date = early.time_stamp
    # print uid, start,start_date, end, end_date
    status = UploadSpeed.query.filter(UploadSpeed.time_stamp < int(end_date), UploadSpeed.uid == uid,
                                       UploadSpeed.time_stamp > int(start_date)).group_by(UploadSpeed.time_stamp).order_by(UploadSpeed.time_stamp.asc())
    data = []
    for s in status:
        t = s.time_stamp
        data.append([t * 1000, s.speed])
    departs = Department.query
    return render_template('status/upload_speed.html', data=json.dumps(data), departs=departs, uid=uid,
                           start=start, end=end)


@bp.route('/current_speed', methods=['POST'])
def current_speed():
    uid = request.form.get('uid')
    speed = UploadStatus.query.filter(UploadStatus.uid == uid, UploadStatus.finish==False, UploadStatus.status == True).\
        order_by(UploadStatus.update_time.desc()).first()
    if not speed:
        return jsonify({'status': 'finish', 'message': '传输完成'})
    return jsonify({'status': 'ok', 'rate': speed.rate, 'percent': speed.percent, 'desc': speed.desc})

@bp.route('/file', methods=['POST'])
@require_user
def file():
    fid = request.form.get('tid', -1, int)
    u = UploadStatus.query.get_or_404(fid)
    data = {
        'tid': u.id,
        'cur': u.current,
        'speed': u.speed,
        'file_name': u.file_name,
        'total': u.total
    }
    return json.dumps(data)


@bp.route('/disk')
@require_user
def disk():
    uid = request.args.get('uid', None, int)
    if not uid or g.user.role != 'admin': # 非管理员用户只能看到自己的
        uid = g.user.id
    user = User.query.get_or_404(uid)
    su, st = get_server_info.get_server_disk(user.email)
    departs = Department.query
    # status = DiskStatus.query
    # client_info = status.order_by(DiskStatus.update_time.desc()).first()
    # su = client_info.used * 1000000
    # st = client_info.total * 100
    # print su, st
    current_app.logger.info("su:" + str(su) + " st:" + str(st))
    client_cur = []
    server_cur = []
    ct = None
    cu = None
    # if client_info:
    #     ct = client_info.total
    #     cu = client_info.used
    #     client_cur = [
    #         ['剩余空间', round((client_info.total - client_info.used) / (1 << 30), 2)],
    #         ['已使用的空间', round(client_info.used / (1 << 30), 2)]]
    if st:
        server_cur = [
            ['剩余空间', round((st - su) / (1 << 30), 2)],
            ['已使用的空间', round(su / (1 << 30), 2)]]
    return render_template('/status/disk.html', departs=departs, uid=uid, client_cur=json.dumps(client_cur),
                           client_total=ct, client_used =cu, server_cur=json.dumps(server_cur), server_total=st, server_used=su)

web/templates/status/disk.html
{% extends 'layout.html' %}

{% block page_css %}
    {{ link('css/status.css') }}
{% endblock %}

{% block content %}
    {{ script('js/bootstrap-datepicker.js') }}
    <div class="row">
        {% if g.user.role == 'admin' %}
            <div class="col-xs-3 left-panel">
                {% for dp in departs %}
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            {{ dp.name }}
                        </div>
                        {% for u in dp.users %}
                            <div class="panel-body">
                                <a href="{{ url_for('status.disk', uid=u.id) }}">
                                    <span>{{ u.name }}</span>&nbsp;
                                    <span>ip: {{ u.ip | none_fill }}</span>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="disk-wap">
            <div class="col-xs-8">
                {% if server_total %}
                    <h3>全部容量: <span style="color: green">{{ server_total | quota_filter }}</span> &nbsp;&nbsp;&nbsp;已使用容量:
                        <span style="color: green">{{ server_used | quota_filter }}</span></h3>
                    <div class="pie-chart" id="server"></div>
                {% else %}
                    <h3>该用户没有服务器网盘使用记录</h3>
                {% endif %}
{#                {% if client_total and client_used %}#}
{#                    <h3>本地磁盘使用情况: <span style="color: green">{{ client_total | quota_filter }}</span> &nbsp;&nbsp;&nbsp;已使用容量:#}
{#                        <span style="color: green">{{ client_used | quota_filter }}</span></h3>#}
{#                    <div class="pie-chart" id="client"></div>#}
{#                {% else %}#}
{#                    <h3>该用户没有本地磁盘使用记录</h3>#}
{#                {% endif %}#}
            </div>
        </div>
    </div>
    {{ script('bower_components/highcharts/highcharts.js') }}
    {{ script('js/disk-status.js') }}
    <script>
        var server_cur = {{ server_cur | safe }};
{#        var client_cur = {{ client_cur | safe }};#}
        loadPieChart("div.disk-wap #server", server_cur, "服务器空间使用情况");
{#        loadPieChart("div.disk-wap #client", client_cur, "客户端空间使用情况");#}
    </script>
{% endblock %}

web/templates/status/repo_status.html
{% extends 'layout.html' %}
{% from 'macro/ui.html' import pagination %}
{% block page_title %}
    资料库同步状态
{% endblock %}

{% block page_css %}
    {{ link('css/status.css') }}
{% endblock %}

{% block content %}
    {{ script('bower_components/bootstrap/dist/js/bootstrap.min.js') }}
    <div class="row">
        {% if g.user.role == 'admin' %}
            <div class="col-xs-3 left-panel">
                {% for dp in departs %}
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            {{ dp.name }}
                        </div>
                        {% for u in dp.users %}
                            <div class="panel-body">
                                <a href="{{ url_for('status.repo', uid=u.id) }}">
                                    <span>{{ u.name }}</span>&nbsp;
                                    <span>ip: {{ u.ip | none_fill }}</span>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="upload-wap">
            <div class="row">
                <div class="col-xs-9">
                    <div class="pb-status">
                        {% if now %}
                            <h3>资料库同步情况：</h3>
                            <strong>同步速度：</strong><span id="rate">{{ now.rate }} kb/s</span>
                            <strong>状态:</strong> <span id="desc">{{ now.desc }}</span>
                            <div class="progress myProgress">
                                <div class="progress-bar progress-bar-success progress-bar-striped active"
                                     role="progressbar" aria-valuemin="0" aria-valuemax="100" id="percent"
                                     style="width:{{ now.percent }}%">
                                    {{ now.percent }} %
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    {% if count > 0 %}
                        <blockquote>共有历史记录：{{ count }} 条 &nbsp;&nbsp;
                            {% if repo_url %}
                                <a class="btn btn-success" href="{{ repo_url }}"
                                   target="_blank">查看详情</a>
                            {% endif %}
                        </blockquote>
                    {% else %}
                        <blockquote>没有同步历史记录</blockquote> {% endif %}
                    <ul id="myTab" class="nav nav-tabs">
                        <li><a href="#suc" data-toggle="tab">传输成功</a></li>
                        <li><a href="#failed" data-toggle="tab">传输失败</a></li>
                    </ul>
                    <div class="tab-content">
                        {% if suc %}
                            <div class="tab-pane" id="suc">
                                {#                                <h3>最近同步情况:</h3>#}

                                <table class="table table-striped">
                                    <thead>
                                    <tr>
                                        <th class="span1">
                                            同步状态
                                        </th>
                                        <th>
                                            开始时间
                                        </th>
                                        <th>
                                            IP
                                        </th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for upload in suc.items %}
                                        <tr>
                                            <td>{{ upload.desc }} &nbsp;{% if upload.status %} 同步成功 {% else %}
                                                <span style="color: red">同步超时 </span> {% endif %}</td>
                                            <td> {{ upload.update_time | time_filter }}</td>
                                            <td> {{ upload.user.ip | none_fill }}</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                                {{ pagination(suc) }}
                            </div>
                        {% endif %}
                        <div class="tab-pane" id="failed">
                            {% if failed %}
                                <div class="tab-pane" id="suc">
                                    {#                                <h3>最近同步情况:</h3>#}

                                    <table class="table table-striped">
                                        <thead>
                                        <tr>
                                            <th class="span1">
                                                同步状态
                                            </th>
                                            <th>
                                                开始时间
                                            </th>
                                            <th>
                                                IP
                                            </th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for upload in failed.items %}
                                            <tr>
                                                <td>{{ upload.desc }} &nbsp;{% if upload.status %} 同步成功 {% else %}
                                                    <span style="color: red">同步超时 </span> {% endif %}</td>
                                                <td> {{ upload.update_time | time_filter }}</td>
                                                <td> {{ upload.user.ip | none_fill }}</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>

                                    {{ pagination(failed) }}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>
        $(function () {
            $('#myTab a:first').tab('show');//初始化显示哪个tab

            $('#myTab a').click(function (e) {
                e.preventDefault();//阻止a链接的跳转行为
                $(this).tab('show');//显示当前选中的链接及关联的content
            });

            var url = gLocals.site_domain + '/status/current_speed'
            var pbRefresh = setInterval(refreshPb, 3000);

            function refreshPb() {
                var myProgress = $("div.myProgress");
                if (myProgress.hasClass("myProgress")) {
                    $.ajax({
                        url: url,
                        method: 'post',
                        data: {
                            'uid': {{ cur }}
                        },
                        success: function (result) {
                            if (result.status == "ok") {
                                $(".pb-status #rate").text(result.rate + "kb/s");
                                $(".pb-status #desc").text(result.desc);
                                $(".pb-status #percent").css({width: result.percent + '%'});
                                $(".pb-status #percent").text(result.percent + '%');
                            } else if (result.status == "finish") {
                                $(".pb-status").hide("myProgress");
                                window.clearInterval(pbRefresh);
                                window.location.reload();
                            }
                        }
                    });
                }
            }

        })
    </script>
{% endblock %}

web/templates/status/upload_speed.html
{% extends "layout.html" %}

{% block page_css %}
    {{ link('css/status.css') }}
    {{ link('css/bootstrap-datetimepicker.min.css') }}
{% endblock %}

{% block content %}
    {{ script('js/bootstrap-datetimepicker.js') }}
    {{ script('bower_components/highcharts/highcharts.js') }}
    <div class="row wrap">
        {% if g.user.role == 'admin' %}
            <div class="col-xs-3 left-panel">
                {% for dp in departs %}
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            {{ dp.name }}
                        </div>
                        {% for u in dp.users %}
                            <div class="panel-body">
                                <a href="{{ url_for('status.upload_speed', uid=u.id) }}">
                                    <span>{{ u.name }}</span>&nbsp;
                                    <span>ip: {{ u.ip | none_fill }}</span>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="disk-wap">
            <div class="row test-bg">
                开始时间:
                <input id="start-date" value="{{ start }}" data-date-format="yyyy-mm-dd hh:ii">
                结束时间:
                <input id="end-date" value="{{ end }}" data-date-format="yyyy-mm-dd hh:ii">
                <a href="javascript:void(0)" class="submit-date">
                    <button>查询</button>
                </a>

                <div class="col-xs-10 line-chart"></div>
            </div>
        </div>
        {{ script('js/disk-status.js') }}
        <script type="text/javascript">
            $(document).ready(function () {
                var startDate = new Date($("#start-date").val());
                var endDate = new Date($("#end-date").val());
                $("#start-date").datetimepicker().on('changeDate', function (ev) {
                    startDate = ev.date.valueOf();
                    if (endDate < startDate) {
                        alert("结束日期不能小于开始日期");
                        $('#start-date').val("");
                    }
                });
                $("#end-date").datetimepicker().on('changeDate', function (ev) {
                    endDate = ev.date.valueOf();
                    if (endDate < startDate) {
                        alert("结束日期不能小于开始日期");
                        $('#end-date').val("");
                    }
                });
            });
            var data = {{ data | safe }};
            Highcharts.setOptions({
                global: {
                    useUTC: false
                }
            });
            $(".line-chart").highcharts({
                title: {
                    text: "文件传输速度"
                },
                subtitle: {
                    text: document.ontouchstart === undefined ?
                            '使用鼠标选定区域缩放' :
                            'Pinch the chart to zoom in'
                },
                chart: {
                    zoomType: 'x'
                },
                xAxis: {
                    type: 'datetime',
                    dateTimeLabelFormats: {
                        second: '%H:%M:%S'
                    },
                    title: {
                        text: '日期'
                    }
                },
                yAxis: {
                    title: {
                        text: '传输平均速度(k/s)'
                    }
                },
                tooltip: {
                    headerFormat: '<b>{series.name}</b><br>',
                    pointFormat: '{point.x:%Y-%m-%d %H:%M:%S} {point.y} k/s'
                },
                series: [
                    {
                        name: '文件平均传输速度',
                        data: data
                    }
                ]
            });
            var uid = {{ uid }};
            $(function () {
                $(document).on('click', '.submit-date', function () {
                    var start = $("#start-date").val();
                    var end = $("#end-date").val();
                    if (start == "" && end == "") return;
                    window.location.href = "upload_speed?uid=" + uid + "&start=" + start + "&" + "end=" + end;
                });
            });
        </script>
    </div>
{% endblock %}

web/templates/status/uploads.html
{% extends 'layout.html' %}
{% from 'macro/ui.html' import pagination %}
{% block page_title %}
    文件上传状态
{% endblock %}

{% block page_css %}
    {{ link('css/status.css') }}
{% endblock %}

{% block content %}
    <div class="row">
        {% if g.user.role == 'admin' %}
            <div class="col-xs-3 left-panel">
                {% for dp in departs %}
                    <div class="panel panel-success">
                        <div class="panel-heading">
                            {{ dp.name }}
                        </div>
                        {% for u in dp.users %}
                            <div class="panel-body">
                                <a href="{{ url_for('status.uploads', uid=u.id) }}">
                                    <span>{{ u.name }}</span>&nbsp;
                                    <span>ip: {{ u.ip | none_fill }}</span>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="upload-wap">
            <div class="col-xs-9 upload-group">
                <h3>正在上传的文件:</h3>
            </div>
            <div class="col-xs-9">
                <h3>已经上传完的文件:</h3>
                {% for fi in finishFiles.items %}
                    <div class="upload-item">
                        <div class="status">
                            上传完成
                        </div>

                        <div class="detail">
                            <table>
                                <tbody>
                                <tr>
                                    <td class="key">文件名：</td>
                                    <td>{{ fi.file_name }}</td>
                                </tr>
                                <tr>
                                    <td class="key">上传日期：</td>
                                    <td>{{ fi.update_time }}</td>
                                </tr>
                                <tr>
                                    <td class="key">平均速度：</td>
                                    <td>{{ fi.speed }}k/s</td>
                                </tr>
                                <tr>
                                    <td class="key">用时：</td>
                                    <td>{{ fi.spend - fi.update_time }}</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                {% endfor %}
                {{ pagination(finishFiles) }}
                <div class="upload-item">
                    <div class="status">
                        上传完成
                    </div>
                    <div class="detail">
                        <table>
                            <tbody>
                            <tr>
                                <td class="key">文件名：</td>
                                <td>hao123.txt</td>
                            </tr>
                            <tr>
                                <td class="key">上传日期：</td>
                                <td>2014-12-11</td>
                            </tr>
                            <tr>
                                <td class="key">平均速度：</td>
                                <td>70k/s</td>
                            </tr>
                            <tr>
                                <td class="key">用时：</td>
                                <td>49s</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {{ script('js/uploads-status.js') }}
    <script>
        var uploadSet = {{ uploadStatus | safe }};
        loadUploadSet(uploadSet);
        //loadProgressBar(12);
    </script>
{% endblock %}